# Ratings-Prediction-Project/ Web Scraping Ratings

In [3]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import selenium.webdriver
from selenium import webdriver 
from datetime import date 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC 
from selenium.webdriver.common.by import By
from dateutil.relativedelta import relativedelta
import csv
import linecache
import sys
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import time

import warnings
warnings.filterwarnings('ignore')

In [7]:
#passing url:
driver = webdriver.Chrome(r"C:\driver\chromedriver.exe")
url='https://www.flipkart.com/search?q=iphone%2011&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
driver.get(url)
#WebElement using xpath:
iphone = driver.find_element_by_xpath('//*[@id="container"]/div/div[3]/div[1]/div[2]/div[26]/div/div/nav/a[5]')
iphone.click()

#extract data from different pages:
start=0
end=200

#creating a dictionary for storing the information after scraping:

rating = []
review = []
full = []

for page in range(start,end):
    ratings=driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']"or"//div[@class='_3LWZlK _1rdVr6 _1BLPMq']")
    reviews=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
    descp=driver.find_elements_by_xpath("//div[@class='t-ZTKy']")
    for i in ratings:
        rating.append(i.text)
    for j in reviews:
        review.append(j.text)
    for k in descp:
        full.append(k.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))
    except:
        driver.get(nxt_button[0].get_attribute('href'))

# all products as per our requirement:

r=rating[0: ]
w=review[0: ]
d=full[0: ]

## Flipkart iphone review:

In [11]:
# # creat Data Frame of the Rating Fullreview and descreption:
items = {'rating':r,"review":w,"desription":d}
iphone_reviews=pd.DataFrame.from_dict(items , orient='index')
iphone_reviews

,0,1,2,3,4,5,6,7,8,9,...,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987
rating,5,5,4,5,5,5,5,5,5,3,...,None,None,None,None,None,None,None,None,None,None
review,Best phone still @25-27K,Absolute rubbish!,Fabulous!,Great product,Good quality product,Perfect product!,Simply awesome,Highly recommended,Best phone still @25-27K,Absolute rubbish!,...,Iphone 5S review,Worthless,Excellent,Must buy!,Classic !!!!,Must buy!,Best phone still @25-27K,Absolute rubbish!,Good phone but not for the power user,Super!
desription,Purchased at BBD @2016 Oct. After 5months of u...,battery service very bad ..Battery not working...,Fast performance to previous iPhone x\nGood ca...,Nithing to say..just awesome,impressively Nice......\nOne of the greatest i...,Nice products thanks flkat,Really satisfied with the Product I received.....,Amazing mobile with great features and excelle...,Purchased at BBD @2016 Oct. After 5months of u...,battery service very bad ..Battery not working...,...,Well the iPhone 5S is here ! its the best iPho...,There was defect in camera lens,awesome\n\nscreen quality better than any othe...,Its doenst need any review i guess so,1.You never gonna feel the quality of this mob...,Still using it in 2019 😂,Purchased at BBD @2016 Oct. After 5months of u...,battery service very bad ..Battery not working...,Apple's iPhone series have been known for thei...,This review is after 6 year of purchasing this...

In [12]:
# Save DataFrame as csv file:
iphone_reviews.to_csv('fk_iphone_reviews.csv', index=False, encoding='utf-8')

In [17]:
fk=pd.read_csv("fk_iphone_reviews.csv")
fk.head()

,Unnamed: 0,Review_title,Reiew_text,Ratings
0,0,Purchased at BBD @2016 Oct. After 5months of u...,Best phone still @25-27K,5.0
1,1,battery service very bad ..Battery not working...,Absolute rubbish!,5.0
2,2,Fast performance to previous iPhone x\nGood ca...,Fabulous!,4.0
3,3,Nithing to say..just awesome,Great product,5.0
4,4,impressively Nice......\nOne of the greatest i...,Good quality product,5.0

## Flipkart review:

In [5]:
#connecting to web driver
driver = webdriver.Chrome(r"C:\driver\chromedriver.exe")

url = "https://www.flipkart.com/"
driver.get(url)
time.sleep(2)
#clicking on cancel buttopn 
driver.find_element_by_xpath("//div[@class='_2QfC02']/button").click()
srch_items = ['laptops', 'Phones','smart watches','Monitors']
title = []
review_text = []
ratings = []
def scrap():    
        for i in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
            review_text.append(i.text)
        for i in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
            title.append(i.text)
        for i in driver.find_elements_by_xpath("//p[@class='_2-N8zT']/../div"):
            ratings.append(i.text)
        return
urls=[]
for i in srch_items:
    # Find the search bar
    srchBar = driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")
    srchBar.clear()
    srchBar.send_keys(i)
    # Clicking on the search button
    driver.find_element_by_xpath("//button[@class='L0Z3Pu']").click()
    time.sleep(3)
    page = []
    for i in driver.find_elements_by_xpath("//nav[@class='yFHi8N']/a"):
        page.append(i.get_attribute('href'))
    for i in page[0:4]:
        driver.get(i)
        time.sleep(3)
        items = driver.find_elements_by_xpath("//a[@class='_1fQZEK']")
        for i in items:
            urls.append(i.get_attribute('href'))

In [6]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    for _ in range(2):
        driver.execute_script("window.scrollBy(0,6000)")
        time.sleep(1)
    # Clicking on all reviews
    try:
        btn=driver.find_element_by_xpath("//div[@class='_1lRcqv']/following::a")
        lnk = btn.get_attribute('href')
        driver.get(lnk)
        time.sleep(1)
    except NoSuchElementException:
        pass

    scrap()        
    try:
        n_page=driver.find_elements_by_xpath("//nav[@class='yFHi8N']/a")
        np=[]
        for i in n_page:
            np.append(i.get_attribute('href'))
        for i in np[0:18]:
            driver.get(i)
            time.sleep(1)
            scrap()
    except: continue

In [7]:
len(ratings), len(review_text), len(title)

(3128, 3128, 3128)

In [29]:
data = list(zip(title,review_text,ratings))
df = pd.DataFrame(data, columns = ["Review_title","Review_text","Ratings"])
df

df.to_csv("flipkart_rating_reviews.csv", index=False, encoding='utf-8')
data=pd.read_csv("flipkart_rating_reviews.csv")

,Review_title,Review_text,Ratings
0,Perfect product!,One of the best Laptop in the market for home ...,5
1,Just wow!,Excellent & far far better than HP laptops. Ve...,5
2,Simply awesome,Best budget laptop if u are student then this ...,5
3,,,
4,,,
...,...,...,...
3123,,,
3124,,,
3125,,,
3126,,,
3127,Brilliant,Good,5

In [15]:
# copying df_train into another object df
df_flipkart = data.copy()
df_flipkart.head()

,Review_title,Review_text,Ratings
0,Perfect product!,One of the best Laptop in the market for home ...,5.0
1,Just wow!,Excellent & far far better than HP laptops. Ve...,5.0
2,Simply awesome,Best budget laptop if u are student then this ...,5.0
3,NaN,NaN,NaN
4,NaN,NaN,NaN

## Amazon review:

In [116]:
#connecting to web driver
driver = webdriver.Chrome(r"C:\driver\chromedriver.exe")
#opening chrome
driver.maximize_window()

url = "https://www.amazon.in/"
driver.get(url)
time.sleep(3)
srch_items = ['laptops','phones','headphones','smart watches', 'Professional Cameras', 'Printers', 
              'Monitors', 'Home theater', 'Router']


title = []
review_text = []
ratings = []

for i in srch_items:
    srchbar = driver.find_element_by_id("twotabsearchtextbox")
    srchbar.send_keys(i)
    driver.find_element_by_id("nav-search-submit-button").click()  #clicking on search button
    time.sleep(1)
    item_url = []
    for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a"):
        item_url.append(i.get_attribute('href'))
    for i in item_url:
        driver.get(i)
        time.sleep(1)
        for _ in range(2):
            driver.execute_script("window.scrollBy(0,6000)")
            time.sleep(1)
            
        # Clicking on see all reviews
        try:
            driver.find_element_by_xpath("//a[@class='a-link-emphasis a-text-bold']").click()
        except:
            pass
        
        url_ = []
        try:
            two_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[4]/td[2]/a")
            url_.append(two_str.get_attribute('href'))
        except: pass
        try:
            three_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[3]/td[2]/a")
            url_.append(three_str.get_attribute('href'))
        except: pass
        try:
            one_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[5]/td[2]/a")
            url_.append(one_str.get_attribute('href'))
        except: pass
        try:
            fiv_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[1]/td[2]/a")
            url_.append(fiv_str.get_attribute('href'))
        except: pass
        try:
            four_str = driver.find_element_by_xpath("//table[@id='histogramTable']/tbody/tr[2]/td[2]/a")
            url_.append(four_str.get_attribute('href'))
        except: pass
        
        for i in url_:
            driver.get(i)
            time.sleep(1)
            for i in range(10):
                ids = driver.find_elements_by_xpath("//div[@class='a-section a-spacing-none review-views celwidget']/div")
                comment_ids = []
                for i in ids:
                    comment_ids.append(i.get_attribute('id'))

                for x in comment_ids:
                    # Extract user ids from each user on a page
                    try:
                        review_title = driver.find_element_by_xpath('//*[@id="' + x +'"]/div/div/div[2]/a[2]/span[1]')
                        title.append(review_title.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        title.append('')

                    try:
                        rating = driver.find_element_by_xpath('//*[@id="viewpoint-R1BI04AV972TX2"]/div[1]/div[4]/i')
                        ratings.append(rating.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        ratings.append('')

                    try:
                        text = driver.find_element_by_xpath('//*[@id="' + x +'"]/div/div/div[4]/span/span')
                        review_text.append(text.get_attribute("innerHTML"))
                    except NoSuchElementException:
                        review_text.append('')
                try:
                    driver.find_element_by_xpath("//ul[@class='a-pagination']/li[2]/a").click()
                    time.sleep(3)
                except : break 
                    
                    
len(ratings), len(title), len(review_text)

(81091, 81091, 81091)

In [125]:
# Creating a dataframe
data = list(zip(title,review_text,ratings))
df = pd.DataFrame(data, columns = ["Review_title","Review_text","Ratings"])
df.to_csv("amazon_rating.csv", index=False, encoding='utf-8')
data=pd.read_csv("amazon_rating.csv")

In [31]:
# copying df_train into another object df
amazon_data = data.copy()

amazon_data=pd.read_csv(r"amazon_rating.csv")
amazon_data.head()

,Unnamed: 0,Review_title,Reiew_text,Ratings
0,0,Think twice before going for it,\n &nbsp;Pros<br>-----<br>- Very light weight...,2.0 out of 5 stars
1,1,Overpriced,\n Overpriced for this mediocre product with ...,2.0 out of 5 stars
2,2,Build quality is not as good as shown in the Ad,\n Did not meet expectations:<br>Takes signif...,3.0 out of 5 stars
3,3,Speed and Visuals makes this a power machine!,\n The speakers and sound quality are patheti...,3.0 out of 5 stars
4,4,Overpriced and unreliable,\n For just i5 11th gen this laptop is way ov...,3.0 out of 5 stars

### Data Scraping completed

## Merging the all scrap data:

In [60]:
import pandas as pd

file1 = r"C:\Users\dell\Web scraping\flipkart_rating_reviews.csv"
file2 = r"C:\Users\dell\Web scraping\fk_iphone_reviews.csv"
file3 = r"C:\Users\dell\Web scraping\amazon_rating.csv"

print("Merging multiple CSV files...")

# merge
dataFrame = pd.concat(
   map(pd.read_csv, [file1, file2, file3]), ignore_index=False )
print(dataFrame)

Merging multiple CSV files...
                                        Review_title  \
0                                   Perfect product!
1                                          Just wow!
2                                     Simply awesome
3                                                NaN
4                                                NaN
...                                              ...
83805  Vfm. Range of Archer c6 or A6 without mu-mimo
83806          USB port is not supported for printer
83807                A best buy for that price range
83808                                Value For Money
83809                                            NaN

                                             Review_text             Ratings  \
0      One of the best Laptop in the market for home ...                 5.0
1      Excellent & far far better than HP laptops. Ve...                 5.0
2      Best budget laptop if u are student then this ...                 5.0
3                                                    NaN                 NaN
4                                                    NaN                 NaN
...                                                  ...                 ...
83805  \n  Same wifi signal range as c6 or the new A6...  4.0 out of 5 stars
83806  \n  USB port is not supporting  printer so I a...  4.0 out of 5 stars
83807  \n  Like : Speed , look and also better range ...  4.0 out of 5 stars
83808  \n  Got it for 2K. Wifi signal in 2.4 Ghz is v...  4.0 out of 5 stars
83809                                                NaN                 NaN

       Unnamed: 0
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
83805     83805.0
83806     83806.0
83807     83807.0
83808     83808.0
83809     83809.0

[88926 rows x 4 columns]

In [61]:
dataFrame

,Review_title,Review_text,Ratings,Unnamed: 0
0,Perfect product!,One of the best Laptop in the market for home ...,5.0,NaN
1,Just wow!,Excellent & far far better than HP laptops. Ve...,5.0,NaN
2,Simply awesome,Best budget laptop if u are student then this ...,5.0,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
83805,Vfm. Range of Archer c6 or A6 without mu-mimo,\n Same wifi signal range as c6 or the new A6...,4.0 out of 5 stars,83805.0
83806,USB port is not supported for printer,\n USB port is not supporting printer so I a...,4.0 out of 5 stars,83806.0
83807,A best buy for that price range,"\n Like : Speed , look and also better range ...",4.0 out of 5 stars,83807.0
83808,Value For Money,\n Got it for 2K. Wifi signal in 2.4 Ghz is v...,4.0 out of 5 stars,83808.0
83809,NaN,NaN,NaN,83809.0

## Data Cleaning :

In [ ]:
dataFrame.drop(columns = 'Unnamed: 0', inplace = True)

In [70]:
print("We have {} Rows and {} Columns in our dataframe".format(dataFrame.shape[0], dataFrame.shape[1]))
dataFrame.head(2)

We have 88926 Rows and 3 Columns in our dataframe

       Review_title                                        Review_text Ratings
0  Perfect product!  One of the best Laptop in the market for home ...     5.0
1         Just wow!  Excellent & far far better than HP laptops. Ve...     5.0

In [ ]:
df_rating = dataFrame.copy()

In [73]:
df_rating.head(3)

       Review_title                                        Review_text Ratings
0  Perfect product!  One of the best Laptop in the market for home ...     5.0
1         Just wow!  Excellent & far far better than HP laptops. Ve...     5.0
2    Simply awesome  Best budget laptop if u are student then this ...     5.0

In [75]:
df_rating

,Review_title,Review_text,Ratings
0,Perfect product!,One of the best Laptop in the market for home ...,5.0
1,Just wow!,Excellent & far far better than HP laptops. Ve...,5.0
2,Simply awesome,Best budget laptop if u are student then this ...,5.0
10,Terrific,Hp laptop is the Best one 👍💞😍\nI am so Happy f...,5.0
11,Mind-blowing purchase,Great laptop\nmust buy\nPerfect for multimedia...,5.0
...,...,...,...
83804,Only one problem,\n Wifi range is very good even for 5ghz sign...,4.0 out of 5 stars
83805,Vfm. Range of Archer c6 or A6 without mu-mimo,\n Same wifi signal range as c6 or the new A6...,4.0 out of 5 stars
83806,USB port is not supported for printer,\n USB port is not supporting printer so I a...,4.0 out of 5 stars
83807,A best buy for that price range,"\n Like : Speed , look and also better range ...",4.0 out of 5 stars
83808,Value For Money,\n Got it for 2K. Wifi signal in 2.4 Ghz is v...,4.0 out of 5 stars

In [110]:
pip install pandas-profiling

Requirement already satisfied: pandas-profiling in c:\users\dell\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (3.5.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.4.2)
Requirement already satisfied: markupsafe~=2.1.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (2.1.1)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (6.0)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (4.64.0)
Requirement already satisfied: scipy>=1.4.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.7.3)
Requirement already satisfied: phik>=0.11.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.12.2)
Requirement already satisfied: visions[type_image_path]==0.7.4 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.21.5)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.9.1)
Requirement already satisfied: requests>=2.24.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (2.27.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (2.11.3)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.11.2)
Requirement already satisfied: missingno>=0.4.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.5.1)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: multimethod>=1.4 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.8)
Requirement already satisfied: joblib~=1.1.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas-profiling) (1.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\dell\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.7.1)
Requirement already satisfied: attrs>=19.3.0 in c:\users\dell\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (21.4.0)
Requirement already satisfied: imagehash in c:\users\dell\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.2.1)
Requirement already satisfied: Pillow in c:\users\dell\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (9.0.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.0.4)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2021.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\dell\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (4.1.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2022.5.18.1)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from tqdm>=4.48.2->pandas-profiling) (0.4.4)
Requirement already satisfied: PyWavelets in c:\users\dell\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.3.0)
Note: you may need to restart the kernel to use updated packages.

In [111]:
pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\dell\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: wheel in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (0.37.1)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (1.21.5)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (1.0.2)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.0)
Note: you may need to restart the kernel to use updated packages.